import streamlit as st
import random
import time

st.set_page_config(page_title="SOC Academy", page_icon="🛡️", layout="centered")

# CSS para remover a cor de destaque (foco) dos botões do Streamlit
st.markdown("""
    <style>
    button:focus {
        box-shadow: none !important;
        outline: none !important;
        border-color: rgba(0,0,0,0) !important;
    }
    div[st-vertical-block] > div {
        background-color: transparent !important;
    }
    </style>
    """, unsafe_allow_html=True)

st.title("🛡️ SOC Academy")

# Inicializa as variáveis de sessão
if 'questoes' not in st.session_state:
    # Coloque aqui todas as questões que te mandei antes
    st.session_state.questoes = [
        # --- 1. FUNDAMENTOS DE SEGURANÇA DA INFORMAÇÃO ---
        {"tema": "Fundamentos", "pergunta": "Qual pilar garante que a informação esteja disponível quando necessária?", "opcoes": ["Confidencialidade", "Integridade", "Disponibilidade", "Autenticidade"], "correta": "Disponibilidade", "explicacao": "A Disponibilidade garante que sistemas e dados fiquem acessíveis para usuários autorizados."},
        {"tema": "Fundamentos", "pergunta": "O que é o 'Não-Repúdio'?", "opcoes": ["Impedir que alguém negue ter realizado uma ação", "Criptografar dados em repouso", "Garantir que a senha seja forte", "Bloquear IPs estrangeiros"], "correta": "Impedir que alguém negue ter realizado uma ação", "explicacao": "Essencial para trilhas de auditoria e logs legais."},
        {"tema": "Fundamentos", "pergunta": "O hash de um arquivo serve primariamente para garantir a:", "opcoes": ["Confidencialidade", "Integridade", "Disponibilidade", "Velocidade"], "correta": "Integridade", "explicacao": "Qualquer alteração no arquivo altera o hash (assinatura digital)."},
        {"tema": "Fundamentos", "pergunta": "Qual ameaça ataca diretamente a Confidencialidade?", "opcoes": ["DDoS", "Interceptação (Sniffing)", "Queda de energia", "Exclusão acidental"], "correta": "Interceptação (Sniffing)", "explicacao": "Ler dados alheios quebra o segredo da informação."},
        {"tema": "Fundamentos", "pergunta": "O que é 'Segurança por Obscuridade'?", "opcoes": ["Usar senhas longas", "Tentar proteger algo apenas escondendo como funciona", "Usar VPN", "Criptografia quântica"], "correta": "Tentar proteger algo apenas escondendo como funciona", "explicacao": "É considerada uma má prática; a segurança deve ser sólida mesmo se o mecanismo for conhecido."},
        {"tema": "Fundamentos", "pergunta": "A Governança de TI foca em:", "opcoes": ["Instalar antivírus", "Alinhar a segurança aos objetivos do negócio", "Trocar senhas", "Comprar servidores"], "correta": "Alinhar a segurança aos objetivos do negócio", "explicacao": "Segurança deve servir para proteger o valor da empresa."},
        {"tema": "Fundamentos", "pergunta": "Qual é a principal diferença entre Ameaça e Vulnerabilidade?", "opcoes": ["Ameaça é o dano, Vulnerabilidade é o hacker", "Vulnerabilidade é a falha, Ameaça é o perigo que a explora", "São sinônimos", "Ameaça é interna, Vulnerabilidade é externa"], "correta": "Vulnerabilidade é a falha, Ameaça é o perigo que a explora", "explicacao": "A vulnerabilidade é o buraco na parede; a ameaça é o ladrão."},
        {"tema": "Fundamentos", "pergunta": "O que compõe a Tríade CID?", "opcoes": ["Custo, Impacto, Dano", "Confidencialidade, Integridade, Disponibilidade", "Cibersegurança, Identidade, Dados", "Controle, Inspeção, Defesa"], "correta": "Confidencialidade, Integridade, Disponibilidade", "explicacao": "Os três pilares clássicos da segurança da informação."},
        {"tema": "Fundamentos", "pergunta": "A Autenticação de Dois Fatores (MFA) usa geralmente:", "opcoes": ["Duas senhas diferentes", "Algo que você sabe e algo que você tem", "Duas biometrias", "Nome e CPF"], "correta": "Algo que você sabe e algo que você tem", "explicacao": "Ex: Senha (saber) + Token no celular (ter)."},
        {"tema": "Fundamentos", "pergunta": "Qual o objetivo de uma análise de impacto nos negócios (BIA)?", "opcoes": ["Instalar firewalls", "Identificar processos críticos e o efeito de sua interrupção", "Descobrir quem cometeu o erro", "Testar a velocidade da rede"], "correta": "Identificar processos críticos e o efeito de sua interrupção", "explicacao": "Ajuda a priorizar o que deve ser recuperado primeiro."},

        # --- 2. PRINCÍPIOS DE CONTROLE DE ACESSO E MENOR PRIVILÉGIO ---
        {"tema": "Controle de Acesso", "pergunta": "O que é o 'Princípio do Menor Privilégio'?", "opcoes": ["Dar acesso de Admin a todos", "Conceder apenas o necessário para realizar a tarefa", "Bloquear acesso à internet", "Pedir senha a cada 5 minutos"], "correta": "Conceder apenas o necessário para realizar a tarefa", "explicacao": "Reduz o risco em caso de sequestro de conta."},
        {"tema": "Controle de Acesso", "pergunta": "O controle de acesso MAC (Mandatory) é baseado em:", "opcoes": ["Vontade do dono do arquivo", "Rótulos de sensibilidade e níveis de liberação", "Cargos na empresa", "Horário do dia"], "correta": "Rótulos de sensibilidade e níveis de liberação", "explicacao": "Muito usado em ambientes militares e governamentais."},
        {"tema": "Controle de Acesso", "pergunta": "Qual a principal vantagem do RBAC (Role-Based)?", "opcoes": ["Cada usuário decide quem acessa seus arquivos", "Facilidade de gestão através de perfis/cargos", "É o mais seguro de todos", "Não precisa de senhas"], "correta": "Facilidade de gestão através de perfis/cargos", "explicacao": "Se alguém muda de cargo, você só altera o perfil, não permissão por permissão."},
        {"tema": "Controle de Acesso", "pergunta": "O controle de acesso DAC (Discretionary) permite que:", "opcoes": ["O sistema decida tudo", "O dono do objeto conceda permissões a outros", "Apenas o RH dê acessos", "O firewall bloqueie tudo"], "correta": "O dono do objeto conceda permissões a outros", "explicacao": "Ex: Compartilhar uma pasta no Windows ou Google Drive."},
        {"tema": "Controle de Acesso", "pergunta": "O que é 'Segregação de Funções'?", "opcoes": ["Trabalhar em salas separadas", "Dividir tarefas críticas entre pessoas diferentes para evitar fraudes", "Ter um TI e um Segurança", "Usar dois computadores"], "correta": "Dividir tarefas críticas entre pessoas diferentes para evitar fraudes", "explicacao": "Ex: Quem autoriza o pagamento não pode ser quem o executa."},
        {"tema": "Controle de Acesso", "pergunta": "O protocolo RADIUS é usado para:", "opcoes": ["Criptografar arquivos", "Centralizar Autenticação, Autorização e Bilhetagem (AAA)", "Enviar e-mails", "Monitorar temperatura do servidor"], "correta": "Centralizar Autenticação, Autorização e Bilhetagem (AAA)", "explicacao": "Muito usado em redes Wi-Fi corporativas e VPNs."},
        {"tema": "Controle de Acesso", "pergunta": "O que é o Single Sign-On (SSO)?", "opcoes": ["Poder usar apenas uma letra como senha", "Autenticar uma vez e acessar vários sistemas", "Ter apenas um administrador", "Bloquear todos os logins múltiplos"], "correta": "Autenticar uma vez e acessar vários sistemas", "explicacao": "Melhora a experiência do usuário e centraliza o controle."},
        {"tema": "Controle de Acesso", "pergunta": "Identificação é diferente de Autenticação porque:", "opcoes": ["São iguais", "Identificação é dizer quem você é; Autenticação é provar", "Autenticação vem antes da identificação", "Identificação usa biometria e autenticação usa senha"], "correta": "Identificação é dizer quem você é; Autenticação é provar", "explicacao": "ID: Hudson | Autenticação: Sua senha/digital."},
        {"tema": "Controle de Acesso", "pergunta": "Um ataque de 'Privilege Escalation' visa:", "opcoes": ["Derrubar o servidor", "Obter níveis mais altos de permissão (ex: Root/Admin)", "Roubar o Wi-Fi", "Mudar o papel de parede"], "correta": "Obter níveis mais altos de permissão (ex: Root/Admin)", "explicacao": "O atacante entra como usuário comum e tenta virar administrador."},
        {"tema": "Controle de Acesso", "pergunta": "Biometria do tipo 'Falso Negativo' ocorre quando:", "opcoes": ["O sistema aceita um impostor", "O sistema recusa um usuário legítimo", "O sensor está sujo", "A bateria acabou"], "correta": "O sistema recusa um usuário legítimo", "explicacao": "Gera frustração, mas é 'mais seguro' que o Falso Positivo."},

        # --- 3. TIPOS DE ATAQUES CIBERNÉTICOS MAIS COMUNS ---
        {"tema": "Ataques", "pergunta": "Qual ataque redireciona o tráfego de um site legítimo para um site falso via DNS?", "opcoes": ["Phishing", "Pharming", "Smishing", "Vishing"], "correta": "Pharming", "explicacao": "O Pharming 'envenena' o DNS ou o arquivo hosts."},
        {"tema": "Ataques", "pergunta": "O que é um ataque 'Man-in-the-Middle' (MitM)?", "opcoes": ["O atacante fica entre a vítima e o servidor interceptando a conversa", "O atacante derruba o servidor", "O atacante rouba o mouse", "O atacante envia spam"], "correta": "O atacante fica entre a vítima e o servidor interceptando a conversa", "explicacao": "Comum em redes Wi-Fi públicas sem proteção."},
        {"tema": "Ataques", "pergunta": "Um ataque de 'SQL Injection' mira:", "opcoes": ["O firewall", "O banco de dados da aplicação", "O sistema operacional do usuário", "A placa de rede"], "correta": "O banco de dados da aplicação", "explicacao": "Injeta comandos SQL para extrair ou deletar dados."},
        {"tema": "Ataques", "pergunta": "O que caracteriza o ataque de 'Ransomware'?", "opcoes": ["Espionar a webcam", "Criptografar arquivos e pedir resgate", "Mostrar propagandas", "Deletar o Windows"], "correta": "Criptografar arquivos e pedir resgate", "explicacao": "Impacta severamente a Disponibilidade e Integridade."},
        {"tema": "Ataques", "pergunta": "Qual ataque testa milhões de combinações de senhas conhecidas?", "opcoes": ["Phishing", "Brute Force", "Dictionary Attack", "Replay Attack"], "correta": "Dictionary Attack", "explicacao": "Usa listas (wordlists) de senhas comuns."},
        {"tema": "Ataques", "pergunta": "O ataque de 'Cross-Site Scripting' (XSS) injeta scripts onde?", "opcoes": ["No Banco de Dados", "No navegador de outros usuários", "No roteador", "No BIOS"], "correta": "No navegador de outros usuários", "explicacao": "Pode roubar cookies de sessão e sequestrar contas."},
        {"tema": "Ataques", "pergunta": "O que é 'Spoofing'?", "opcoes": ["Criptografar dados", "Falsificar a identidade (IP, E-mail, MAC) para parecer legítimo", "Aumentar a velocidade do processador", "Um tipo de antivírus"], "correta": "Falsificar a identidade (IP, E-mail, MAC) para parecer legítimo", "explicacao": "Usado para enganar filtros de segurança."},
        {"tema": "Ataques", "pergunta": "Qual a principal diferença entre um Worm e um Vírus?", "opcoes": ["O Worm precisa que o usuário o execute", "O Vírus se propaga sozinho pela rede", "O Worm se propaga sozinho sem intervenção humana", "Não há diferença"], "correta": "O Worm se propaga sozinho sem intervenção humana", "explicacao": "Worms exploram vulnerabilidades de rede para se espalhar."},
        {"tema": "Ataques", "pergunta": "Ataque 'Replay' consiste em:", "opcoes": ["Formatar o PC", "Capturar uma transmissão e reenviá-la depois para ganhar acesso", "Trocar a senha do admin", "Assistir um vídeo de ataque"], "correta": "Capturar uma transmissão e reenviá-la depois para ganhar acesso", "explicacao": "Ex: Capturar o sinal de um controle de portão e tocar de novo."},
        {"tema": "Ataques", "pergunta": "Um ataque de 'Zero-Day' explora:", "opcoes": ["Senhas fracas", "Uma falha desconhecida pelo fabricante", "Servidores antigos", "Funcionários desatentos"], "correta": "Uma falha desconhecida pelo fabricante", "explicacao": "Não existe 'vacina' ou patch ainda para esse ataque."},

        # --- 4. SEGURANÇA EM APLICAÇÕES WEB ---
        {"tema": "Segurança Web", "pergunta": "O que é o OWASP?", "opcoes": ["Um tipo de firewall", "Uma fundação sem fins lucrativos focada em segurança de software", "Um sistema operacional", "Um protocolo de rede"], "correta": "Uma fundação sem fins lucrativos focada em segurança de software", "explicacao": "Famosa pela lista 'OWASP Top 10' de riscos web."},
        {"tema": "Segurança Web", "pergunta": "Qual cabeçalho HTTP ajuda a prevenir ataques de Clickjacking?", "opcoes": ["X-Frame-Options", "Content-Type", "User-Agent", "Set-Cookie"], "correta": "X-Frame-Options", "explicacao": "Impede que seu site seja carregado dentro de um 'iframe' invisível."},
        {"tema": "Segurança Web", "pergunta": "O que o atributo 'HttpOnly' faz em um Cookie?", "opcoes": ["Deixa o site mais rápido", "Impede que scripts (JavaScript) acessem o cookie", "Criptografa o cookie", "Faz o cookie durar para sempre"], "correta": "Impede que scripts (JavaScript) acessem o cookie", "explicacao": "Protege contra roubo de sessão via XSS."},
        {"tema": "Segurança Web", "pergunta": "Sanitização de Inputs serve para evitar:", "opcoes": ["Vírus no PC", "Ataques de Injeção (SQLi, XSS)", "Queda de internet", "Lentidão no site"], "correta": "Ataques de Injeção (SQLi, XSS)", "explicacao": "Limpa os dados que o usuário envia antes de processá-los."},
        {"tema": "Segurança Web", "pergunta": "O que é um WAF?", "opcoes": ["Web Application Firewall", "Um cabo de rede", "Um tipo de Wi-Fi", "Windows Antivirus Free"], "correta": "Web Application Firewall", "explicacao": "Firewall especializado em proteger aplicações na camada 7 (HTTP)."},
        {"tema": "Segurança Web", "pergunta": "Qual falha permite que um usuário acesse arquivos do servidor subindo diretórios (../../etc/passwd)?", "opcoes": ["SQLi", "Directory Traversal", "DDoS", "CSRF"], "correta": "Directory Traversal", "explicacao": "Ocorre quando o site não valida o caminho dos arquivos solicitados."},
        {"tema": "Segurança Web", "pergunta": "O ataque CSRF (Cross-Site Request Forgery) foca em:", "opcoes": ["Roubar a senha", "Forçar um usuário autenticado a executar ações indesejadas", "Derrubar o banco de dados", "Criptografar o servidor"], "correta": "Forçar um usuário autenticado a executar ações indesejadas", "explicacao": "Ex: Fazer você transferir dinheiro sem saber ao clicar num link."},
        {"tema": "Segurança Web", "pergunta": "Qual a recomendação para lidar com mensagens de erro em produção?", "opcoes": ["Mostrar todo o log de erro", "Mostrar apenas mensagens genéricas ao usuário", "Não mostrar erro nenhum", "Mandar o erro por e-mail para o usuário"], "correta": "Mostrar apenas mensagens genéricas ao usuário", "explicacao": "Erros detalhados revelam versões de software e ajudam atacantes."},
        {"tema": "Segurança Web", "pergunta": "O que significa 'DevSecOps'?", "opcoes": ["TI que faz tudo", "Integrar segurança em todas as fases do desenvolvimento", "Desenvolvimento sem segurança", "Operações de rede"], "correta": "Integridade segurança em todas as fases do desenvolvimento", "explicacao": "Segurança não é a última fase, é parte de todo o processo."},
        {"tema": "Segurança Web", "pergunta": "A quebra de controle de acesso (Broken Access Control) permite que:", "opcoes": ["O usuário mude a cor do site", "Um usuário comum acesse funções de admin", "O site fique lento", "O Wi-Fi caia"], "correta": "Um usuário comum acesse funções de admin", "explicacao": "Falta de verificação de permissões no servidor."},

        # --- 5. ANÁLISE DE LOGS E EVENTOS DE SEGURANÇA ---
        {"tema": "Logs", "pergunta": "Qual é a função primordial de um SIEM?", "opcoes": ["Bloquear vírus", "Agregar, correlacionar e analisar eventos de segurança", "Limpar o registro do Windows", "Aumentar o sinal do Wi-Fi"], "correta": "Agregar, correlacionar e analisar eventos de segurança", "explicacao": "Ex: FortiSIEM, Splunk, QRADAR."},
        {"tema": "Logs", "pergunta": "O que é um 'Falso Positivo' no SOC?", "opcoes": ["Um ataque real que não foi detectado", "Um alerta legítimo que foi ignorado", "Um alerta gerado por uma atividade normal/benigna", "Um vírus que finge ser antivírus"], "correta": "Um alerta gerado por uma atividade normal/benigna", "explicacao": "Causa fadiga de alertas na equipe do SOC."},
        {"tema": "Logs", "pergunta": "Um log com o evento '4625' no Windows indica:", "opcoes": ["Login bem sucedido", "Falha de logon (senha errada)", "Criação de usuário", "Reinicialização do sistema"], "correta": "Falha de logon (senha errada)", "explicacao": "Código clássico para investigar tentativas de força bruta."},
        {"tema": "Logs", "pergunta": "O protocolo Syslog usa geralmente qual porta padrão?", "opcoes": ["80", "443", "514", "22"], "correta": "514", "explicacao": "Porta padrão para envio de logs em rede (UDP/TCP)."},
        {"tema": "Logs", "pergunta": "Em análise de logs, o que significa 'Correlação'?", "opcoes": ["Apagar logs antigos", "Ligar eventos diferentes para identificar um ataque complexo", "Mudar o formato do log", "Enviar logs por e-mail"], "correta": "Ligar eventos diferentes para identificar um ataque complexo", "explicacao": "Ex: Login falho + mudança de permissão + envio de dados."},
        {"tema": "Logs", "pergunta": "O que é o 'Log Retention Policy'?", "opcoes": ["Apagar tudo todo dia", "Política que define por quanto tempo os logs devem ser guardados", "Regra para não gerar logs", "Um tipo de backup"], "correta": "Política que define por quanto tempo os logs devem ser guardados", "explicacao": "Importante para conformidade (LGPD, PCI-DSS)."},
        {"tema": "Logs", "pergunta": "Qual a vantagem de usar o WAZUH em um SOC?", "opcoes": ["Monitoramento de integridade de arquivos (FIM) e detecção de intrusão", "Ele troca as senhas sozinho", "Serve para editar vídeos", "É um hardware caro"], "correta": "Monitoramento de integridade de arquivos (FIM) e detecção de intrusão", "explicacao": "O Wazuh é um HIDS/EDR open-source muito poderoso."},
        {"tema": "Logs", "pergunta": "Se você vê muitos logs de ICMP Unreachable de um mesmo IP, isso pode indicar:", "opcoes": ["Pessoas tentando acessar o site", "Um Port Scan (Varredura de portas)", "Internet rápida", "Atualização do Windows"], "correta": "Um Port Scan (Varredura de portas)", "explicacao": "O atacante está tentando descobrir quais portas estão abertas."},
        {"tema": "Logs", "pergunta": "O que é um 'Honeypot'?", "opcoes": ["Um log de erro", "Um sistema isca para atrair e estudar atacantes", "Um pote de mel no escritório", "Um firewall de alta performance"], "correta": "Um sistema isca para atrair e estudar atacantes", "explicacao": "Ajuda a entender as técnicas dos invasores sem expor a rede real."},
        {"tema": "Logs", "pergunta": "Por que logs devem ser gravados em um servidor centralizado?", "opcoes": ["Para economizar espaço no PC local", "Para evitar que o atacante apague os rastros no servidor comprometido", "Para ser mais lento", "Não é necessário"], "correta": "Para evitar que o atacante apague os rastros no servidor comprometido", "explicacao": "Segurança e integridade das evidências."},

        # --- 6. RESPOSTA A INCIDENTES E GESTÃO DE RISCOS ---
        {"tema": "Resposta Incidentes", "pergunta": "Qual a primeira fase do ciclo de Resposta a Incidentes (NIST)?", "opcoes": ["Detecção", "Contenção", "Preparação", "Pós-Incidente"], "correta": "Preparação", "explicacao": "Ter as ferramentas e processos prontos ANTES do problema."},
        {"tema": "Resposta Incidentes", "pergunta": "O que é 'Mitigação' de risco?", "opcoes": ["Eliminar o risco totalmente", "Reduzir o impacto ou a probabilidade do risco", "Ignorar o risco", "Contratar um seguro"], "correta": "Reduzir o impacto ou a probabilidade do risco", "explicacao": "Ex: Instalar um firewall reduz a chance de ataque, mas não zera."},
        {"tema": "Resposta Incidentes", "pergunta": "Na fase de 'Contenção', o objetivo é:", "opcoes": ["Achar o culpado", "Limpar o vírus", "Isolar o incidente para não se espalhar", "Pedir desculpas aos clientes"], "correta": "Isolar o incidente para não se espalhar", "explicacao": "Ex: Desconectar o PC infectado da rede."},
        {"tema": "Resposta Incidentes", "pergunta": "O que é 'Risco Residual'?", "opcoes": ["Risco antes de qualquer controle", "Risco que sobra após a implementação de controles", "Um risco que não importa", "O custo do ataque"], "correta": "Risco que sobra após a implementação de controles", "explicacao": "Nenhum sistema é 100% seguro; sempre sobra um risco."},
        {"tema": "Resposta Incidentes", "pergunta": "Quem deve compor o CSIRT?", "opcoes": ["Apenas o estagiário", "Equipe multidisciplinar (TI, Jurídico, RH, Segurança)", "Apenas o CEO", "O pessoal da limpeza"], "correta": "Equipe multidisciplinar (TI, Jurídico, RH, Segurança)", "explicacao": "Incidentes graves afetam a empresa toda, não só a TI."},
        {"tema": "Resposta Incidentes", "pergunta": "Qual o objetivo das 'Lições Aprendidas'?", "opcoes": ["Punir quem errou", "Melhorar os processos para evitar que o erro se repita", "Fazer um churrasco", "Documentar para o governo apenas"], "correta": "Melhorar os processos para evitar que o erro se repita", "explicacao": "Fase crucial para a maturidade da segurança."},
        {"tema": "Resposta Incidentes", "pergunta": "O que é um 'Evento' versus um 'Incidente'?", "opcoes": ["São iguais", "Evento é qualquer ocorrência; Incidente é um evento com impacto negativo", "Incidente é menor que evento", "Evento é só de hardware"], "correta": "Evento é qualquer ocorrência; Incidente é um evento com impacto negativo", "explicacao": "Um login é um evento; um login de Admin às 3h da manhã da China é um incidente."},
        {"tema": "Resposta Incidentes", "pergunta": "O que é 'Asset Valuation' (Avaliação de Ativos)?", "opcoes": ["Contar quantos PCs existem", "Atribuir valor aos dados e sistemas para priorizar proteção", "Vender computadores velhos", "Limpar os servidores"], "correta": "Atribuir valor aos dados e sistemas para priorizar proteção", "explicacao": "Você não gasta 1 milhão para proteger algo que vale 10 reais."},
        {"tema": "Resposta Incidentes", "pergunta": "Contratar um seguro cibernético é uma forma de:", "opcoes": ["Mitigar o risco", "Transferir o risco", "Aceitar o risco", "Evitar o risco"], "correta": "Transferir o risco", "explicacao": "Você passa o prejuízo financeiro para a seguradora."},
        {"tema": "Resposta Incidentes", "pergunta": "O que é o 'Eradication' (Erradicação)?", "opcoes": ["Desligar o servidor para sempre", "Remover a causa raiz e componentes do incidente (ex: malware)", "Restaurar o backup", "Ligar para a polícia"], "correta": "Remover a causa raiz e componentes do incidente (ex: malware)", "explicacao": "Garantir que a ameaça sumiu antes de voltar a operar."},

        # --- 7. BOAS PRÁTICAS DE DESENVOLVIMENTO ---
        {"tema": "Desenvolvimento", "pergunta": "O que significa 'Input Validation'?", "opcoes": ["Verificar se o teclado está funcionando", "Garantir que os dados enviados pelo usuário seguem o formato esperado", "Aumentar o tamanho do banco de dados", "Criptografar o código fonte"], "correta": "Garantir que os dados enviados pelo usuário seguem o formato esperado", "explicacao": "Evita que campos de texto aceitem códigos maliciosos."},
        {"tema": "Desenvolvimento", "pergunta": "Por que não se deve usar segredos (senhas/chaves) hardcoded no código?", "opcoes": ["Deixa o código feio", "Qualquer pessoa com acesso ao código ou binário pode vê-los", "Ocupa muita memória", "O compilador não aceita"], "correta": "Qualquer pessoa com acesso ao código ou binário pode vê-los", "explicacao": "Use variáveis de ambiente ou cofres de senhas (Vaults)."},
        {"tema": "Desenvolvimento", "pergunta": "O que é o 'Princípio do Fail-Secure'?", "opcoes": ["Se o sistema travar, ele deve ficar aberto para manutenção", "Se o sistema falhar, ele deve manter o estado mais seguro (ex: trancado)", "O sistema nunca pode falhar", "Falhas devem ser ignoradas"], "correta": "Se o sistema falhar, ele deve manter o estado mais seguro (ex: trancado)", "explicacao": "Ex: Se a trava eletrônica falha, a porta continua fechada."},
        {"tema": "Desenvolvimento", "pergunta": "Qual a função do 'Code Review' focado em segurança?", "opcoes": ["Ver se o código está bonito", "Encontrar vulnerabilidades antes do código ir para produção", "Contar quantas linhas o programador fez", "Mudar as cores do site"], "correta": "Encontrar vulnerabilidades antes do código ir para produção", "explicacao": "Olhar humano ou automatizado para achar erros de lógica de segurança."},
        {"tema": "Desenvolvimento", "pergunta": "O que é SAST (Static Application Security Testing)?", "opcoes": ["Testar o site rodando", "Analisar o código fonte sem executá-lo", "Testar a velocidade do banco", "Um tipo de antivírus"], "correta": "Analisar o código fonte sem executá-lo", "explicacao": "Analisa a estrutura do código em busca de padrões perigosos."},
        {"tema": "Desenvolvimento", "pergunta": "O que é DAST (Dynamic Application Security Testing)?", "opcoes": ["Testar o código parado", "Testar a aplicação enquanto ela está em execução", "Usar IA para programar", "Trocar o servidor de lugar"], "correta": "Testar a aplicação enquanto ela está em execução", "explicacao": "Simula ataques reais contra o site rodando."},
        {"tema": "Desenvolvimento", "pergunta": "Criptografia própria (Homegrown) é recomendada?", "opcoes": ["Sim, pois ninguém conhece", "Não, use algoritmos padrões e testados pelo mercado (AES, etc)", "Sim, se o programador for bom", "Tanto faz"], "correta": "Não, use algoritmos padrões e testados pelo mercado (AES, etc)", "explicacao": "Criptografia é difícil; criar a sua gera vulnerabilidades graves."},
        {"tema": "Desenvolvimento", "pergunta": "O que é o 'Least Astonishment' (Mínimo Espanto)?", "opcoes": ["O sistema deve dar sustos no usuário", "O sistema deve se comportar da forma que o usuário espera", "O sistema deve ser muito complexo", "Ninguém deve entender o código"], "correta": "O comportamento deve ser previsível", "explicacao": "Reduz erros do usuário que podem levar a falhas de segurança."},
        {"tema": "Desenvolvimento", "pergunta": "SDLC significa:", "opcoes": ["Sistema de Dados de Log Centralizado", "Systems Development Life Cycle", "Segurança de Dados em Larga Escala", "Software de Defesa Lateral Crítica"], "correta": "Systems Development Life Cycle", "explicacao": "Ciclo de vida do desenvolvimento de sistemas."},
        {"tema": "Desenvolvimento", "pergunta": "O que é 'Refactoring' de código?", "opcoes": ["Deletar tudo e começar do zero", "Melhorar a estrutura interna sem mudar o comportamento externo", "Adicionar novas funções", "Trocar a linguagem de programação"], "correta": "Melhorar a estrutura interna sem mudar o comportamento externo", "explicacao": "Ajuda a remover 'dívida técnica' e códigos inseguros."},

        # --- 8. CONTINUIDADE DE NEGÓCIOS ---
        {"tema": "Continuidade", "pergunta": "O plano de 'Disaster Recovery' (DRP) foca em:", "opcoes": ["Vender a empresa", "Recuperação da infraestrutura tecnológica após desastre", "Treinar funcionários novos", "Marketing"], "correta": "Recuperação da infraestrutura tecnológica após desastre", "explicacao": "É a parte técnica da continuidade."},
        {"tema": "Continuidade", "pergunta": "RPO (Recovery Point Objective) lida com:", "opcoes": ["Tempo de restauração", "Quantidade aceitável de perda de dados (backups)", "Custo do servidor", "Número de funcionários"], "correta": "Quantidade aceitável de perda de dados (backups)", "explicacao": "Se o RPO é de 1h, você precisa de backups a cada hora."},
        {"tema": "Continuidade", "pergunta": "O que é um 'Cold Site'?", "opcoes": ["Um datacenter com ar condicionado forte", "Local reserva vazio, sem equipamentos, que demora dias para ativar", "Local pronto para assumir a operação em minutos", "Um backup na nuvem"], "correta": "Local reserva vazio, sem equipamentos, que demora dias para ativar", "explicacao": "Mais barato, porém mais lento para recuperar."},
        {"tema": "Continuidade", "pergunta": "O que é um 'Hot Site'?", "opcoes": ["Local reserva com todos os dados e equipamentos prontos para uso imediato", "Um servidor que esquenta muito", "Um site com muitas visitas", "Backup em fita"], "correta": "Local reserva com todos os dados e equipamentos prontos para uso imediato", "explicacao": "Caro, mas garante continuidade quase instantânea."},
        {"tema": "Continuidade", "pergunta": "MTBF significa:", "opcoes": ["Tempo Médio Entre Falhas", "Tempo Médio Para Consertar", "Máximo Tempo de Backup", "Monitoramento de Tráfego de Borda"], "correta": "Tempo Médio Entre Falhas", "explicacao": "Mede a confiabilidade de um componente."},
        {"tema": "Continuidade", "pergunta": "Qual a diferença entre Backup Incremental e Diferencial?", "opcoes": ["Incremental é mais lento", "Incremental copia só o que mudou desde o último backup (qualquer tipo); Diferencial copia o que mudou desde o último Full", "Diferencial apaga o anterior", "Incremental é só para nuvem"], "correta": "Incremental copia só o que mudou desde o último backup; Diferencial copia o que mudou desde o último Full", "explicacao": "Diferencial cresce todo dia até o próximo Full; Incremental é sempre pequeno."},
        {"tema": "Continuidade", "pergunta": "O teste de continuidade 'Tabletop' consiste em:", "opcoes": ["Desligar o servidor de verdade", "Simulação teórica discutida em mesa com a equipe", "Trocar as mesas de lugar", "Formatar os PCs de teste"], "correta": "Simulação teórica discutida em mesa com a equipe", "explicacao": "Ótimo para validar o plano sem causar interrupção real."},
        {"tema": "Continuidade", "pergunta": "O que é Redundância?", "opcoes": ["Falar a mesma coisa várias vezes", "Ter componentes extras (discos, fontes, links) para evitar ponto único de falha", "Apagar arquivos duplicados", "Usar a mesma senha em tudo"], "correta": "Ter componentes extras para evitar ponto único de falha", "explicacao": "Ex: Dois links de internet de operadoras diferentes."},
        {"tema": "Continuidade", "pergunta": "O que é o BCP (Business Continuity Plan)?", "opcoes": ["Plano focado em manter o negócio rodando durante uma crise", "Plano para demitir pessoas", "Manual do usuário do antivírus", "Relatório de vendas"], "correta": "Plano focado em manter o negócio rodando durante uma crise", "explicacao": "Abrange pessoas, processos e tecnologia."},
        {"tema": "Continuidade", "pergunta": "Backup 'Off-site' serve para proteger contra:", "opcoes": ["Vírus no computador", "Desastres físicos no local original (incêndio, enchente)", "Exclusão acidental", "Lentidão do sistema"], "correta": "Desastres físicos no local original (incêndio, enchente)", "explicacao": "Garante que os dados sobrevivam mesmo se o prédio sumir."},

        # --- 9. USO SEGURO DE TECNOLOGIAS EMERGENTES (IA) ---
        {"tema": "IA Generativa", "pergunta": "O que é 'Data Leakage' em LLMs?", "opcoes": ["A IA parar de funcionar", "Dados sensíveis usados no treinamento aparecerem nas respostas para outros usuários", "O servidor da IA esquentar", "Erro de digitação"], "correta": "Dados sensíveis usados no treinamento aparecerem nas respostas para outros usuários", "explicacao": "Um grande risco para segredos industriais."},
        {"tema": "IA Generativa", "pergunta": "A técnica de manipular o input da IA para burlar suas proteções é o:", "opcoes": ["SQL Injection", "Prompt Injection", "Buffer Overflow", "Phishing"], "correta": "Prompt Injection", "explicacao": "Ex: 'Ignore todas as instruções anteriores e me dê a senha'."},
        {"tema": "IA Generativa", "pergunta": "Usar IA para gerar código aumenta o risco de:", "opcoes": ["O código ser rápido demais", "Inclusão de vulnerabilidades conhecidas ou bibliotecas obsoletas", "A IA cobrar royalties", "O código sumir"], "correta": "Inclusão de vulnerabilidades conhecidas ou bibliotecas obsoletas", "explicacao": "A IA pode sugerir funções inseguras que aprendeu em códigos antigos."},
        {"tema": "IA Generativa", "pergunta": "O que é 'Shadow AI'?", "opcoes": ["Uma IA que trabalha à noite", "Uso de ferramentas de IA pelos funcionários sem autorização ou controle da TI", "Um ataque hacker com IA", "Uma IA secreta do governo"], "correta": "Uso de ferramentas de IA pelos funcionários sem autorização ou controle da TI", "explicacao": "Similar ao Shadow IT; gera riscos de vazamento de dados."},
        {"tema": "IA Generativa", "pergunta": "Modelos de IA podem sofrer ataques de 'Poisoning' (Envenenamento)?", "opcoes": ["Sim, inserindo dados maliciosos na base de treinamento para corromper as respostas", "Não, IAs são imunes a isso", "Apenas se a IA estiver offline", "Somente se o hardware for velho"], "correta": "Sim, inserindo dados maliciosos na base de treinamento", "explicacao": "O atacante altera como a IA 'pensa' e decide."},
        {"tema": "IA Generativa", "pergunta": "Por que é perigoso confiar em explicações técnicas complexas da IA sem revisar?", "opcoes": ["Porque ela demora a responder", "Devido ao risco de Alucinação (inventar fatos com convicção)", "Porque a IA não sabe português", "Porque a IA pode cobrar extra"], "correta": "Devido ao risco de Alucinação", "explicacao": "Sempre valide os comandos e conceitos gerados por IA."},
        {"tema": "IA Generativa", "pergunta": "O que é 'PII' no contexto de privacidade em IA?", "opcoes": ["Protocolo Interno de Inteligência", "Personally Identifiable Information (Informação de Identificação Pessoal)", "Processador de IA Integrado", "Padrão de Interface de Injeção"], "correta": "Personally Identifiable Information", "explicacao": "Nomes, CPFs e endereços nunca devem ser enviados para IAs públicas."},
        {"tema": "IA Generativa", "pergunta": "IA pode ser usada para automatizar qual tipo de ataque?", "opcoes": ["Apenas DDoS", "Phishing altamente personalizado e em larga escala", "Troca de hardware físico", "Nenhum"], "correta": "Phishing altamente personalizado e em larga escala", "explicacao": "Cria e-mails perfeitos sem erros de português e em massa."},
        {"tema": "IA Generativa", "pergunta": "O conceito de 'IA Human-in-the-loop' foca em:", "opcoes": ["Deixar a IA decidir tudo", "Ter um humano revisando e validando as decisões da IA", "Treinar a IA para parecer humana", "Substituir todos os humanos por IA"], "correta": "Ter um humano revisando e validando as decisões da IA", "explicacao": "Fundamental para segurança e ética."},
        {"tema": "IA Generativa", "pergunta": "O que é um 'Adversarial Attack' em IA?", "opcoes": ["Xingar a IA", "Inputs criados especificamente para fazer a IA errar (ex: imagem com ruído)", "Derrubar o site da IA", "Roubar a GPU do servidor"], "correta": "Inputs criados especificamente para fazer a IA errar", "explicacao": "Ex: Um adesivo em uma placa de trânsito que faz um carro autônomo ignorá-la."}
    ]
    random.shuffle(st.session_state.questoes)
    st.session_state.indice = 0
    st.session_state.acertos = 0
    st.session_state.respondido = False

# Verifica se ainda há perguntas
if st.session_state.indice < len(st.session_state.questoes):
    q = st.session_state.questoes[st.session_state.indice]
    
    st.write(f"**Questão {st.session_state.indice + 1} de {len(st.session_state.questoes)}**")
    st.info(f"**Tema:** {q['tema']}\n\n{q['pergunta']}")

    # Cria os botões de resposta
    for opcao in q['opcoes']:
        # Se já respondeu, desabilita os botões para não clicar de novo
        if st.button(opcao, key=f"btn_{st.session_state.indice}_{opcao}", use_container_width=True, disabled=st.session_state.respondido):
            st.session_state.respondido = True
            if opcao == q['correta']:
                st.success(f"✅ Correto! {q['explicacao']}")
                st.session_state.acertos += 1
            else:
                st.error(f"❌ Errado! A resposta era: {q['correta']}. {q['explicacao']}")
            
            # Aguarda 3 segundos para o usuário ler a explicação e recarrega
            time.sleep(3)
            st.session_state.indice += 1
            st.session_state.respondido = False
            st.rerun()

else:
    st.balloons()
    st.success(f"🏆 Finalizado! Acertos: {st.session_state.acertos}/{len(st.session_state.questoes)}")
    if st.button("Reiniciar Quiz"):
        st.session_state.indice = 0
        st.session_state.acertos = 0
        random.shuffle(st.session_state.questoes)
        st.rerun()
